### PR TITLE
Add snap_manageAccounts RPC handler.

### PR DESCRIPTION
**Pull request by tmpfs**

### CODE REVIEW

**Comment by ritave** [comment]
Closing due to inactivity. Work on SIP-2 keyrings is ahead of this PR as well

**Comment by kumavis** [comment]
see https://github.com/MetaMask/SIPs/discussions/10 for discussion

**Comment by kumavis** [comment]
(accidentally reopened)

**Comment by kumavis** [comment]
later iterations
https://github.com/MetaMask/metamask-extension/pull/16107
https://github.com/MetaMask/snaps-monorepo/discussions/821

**Pull request closed without merging**
