### PR TITLE
BREAKING: Remove `snap_getAppKey`

### PR DESCRIPTION
**Pull request by FrederikBolding**
Removes `snap_getAppKey` as we don't want to support this API for stable. We will add a replacement RPC method for that in the future.

### CODE REVIEW

**Comment by Mrtenz** [comment]
I don't think this should be merged until we have a replacement.

**Comment by FrederikBolding** [comment]
Not sure I agree. It's not a documented function, I would think its not much used. It is very much a legacy function from a previous iteration of snaps.

**Comment by ritave** [comment]
[Currently used in BLS example](https://github.com/MetaMask/snaps-monorepo/blob/00df08a55371b5bf7e943511bf2d830bb6532253/packages/examples/examples/bls-signer/src/index.js#L52)

**Comment by FrederikBolding** [comment]
> [Currently used in BLS example](https://github.com/MetaMask/snaps-monorepo/blob/00df08a55371b5bf7e943511bf2d830bb6532253/packages/examples/examples/bls-signer/src/index.js#L52)

Another reason to throw those examples out 😅

**Review by Mrtenz — APPROVED** [review]

**Pull request merged**
